export default {
	THEME_CHANGE: "THEME_CHANGE",	//改变主题
	THEME_INIT: "THEME_INIT",		//默认主题
	SHOW_THEME_VIEW: "SHOW_THEME_VIEW", //显示主题页
	HOME_REFRESH:'POPULAR_REFRESH',	//刷新
	HOME_REFRESH_FAIL:'POPULAR_REFRESH_FAIL',	//下拉刷新失败
	HOME_REFRESH_SUCCESS:'POPULAR_REFRESH_SUCCESS',	//下拉刷新成功
	HOME_LOAD_MORE_SUCCESS:'POPULAR_LOAD_MORE_SUCCESS',	// 上拉加载更多成功
	HOME_LOAD_MORE_FAIL:'POPULAR_LOAD_MORE_FAIL',	// 上拉加载更多失败
}