export default {
	THEME_CHANGE: "THEME_CHANGE",	//改变主题
	THEME_INIT: "THEME_INIT",		//默认主题
	SHOW_THEME_VIEW: "SHOW_THEME_VIEW", //显示主题页
	HOME_REFRESH:'HOME_REFRESH',	//刷新
	HOME_REFRESH_FAIL:'HOME_REFRESH_FAIL',	//下拉刷新失败
	HOME_REFRESH_SUCCESS:'HOME_REFRESH_SUCCESS',	//下拉刷新成功
	HOME_LOAD_MORE_SUCCESS:'HOME_LOAD_MORE_SUCCESS',	// 上拉加载更多成功
	HOME_LOAD_MORE_FAIL:'HOME_LOAD_MORE_FAIL',	// 上拉加载更多失败
	NEWS_DETAIL:'NEWS_DETAIL',		//获取新闻详情页
	Foreign_REFRESH:'Foreign_REFRESH',	//际取新闻刷新
	Foreign_REFRESH_FAIL:'Foreign_REFRESH_FAIL',	//际取新闻下拉刷新失败
	Foreign_REFRESH_SUCCESS:'Foreign_REFRESH_SUCCESS',	//际取新闻下拉刷新成功
	Foreign_LOAD_MORE_SUCCESS:'Foreign_LOAD_MORE_SUCCESS',	// 际取新闻上拉加载更多成功
	Foreign_LOAD_MORE_FAIL:'Foreign_LOAD_MORE_FAIL',	// 际取新闻上拉加载更多失败
	Foreign_DETAIL:'NEWS_DETAIL',		//获国际取新闻详情页
	FAVORITE_LOAD_DATA:"FAVORITE_LOAD_DATA",	//获取收藏数据
	FAVORITE_LOAD_SUCCESS:"FAVORITE_LOAD_SUCCESS",	//收藏成功
	FAVORITE_LOAD_FAIL:"FAVORITE_LOAD_FAIL",	//收藏失败
	FAVORITE_EDIT_SUCCESS:"FAVORITE_EDIT_SUCCESS",	//添加收藏成功
	USER_LOGIN:"USER_LOGIN",	//用户登录
	USER_LOGIN_SUCCESS:"USER_LOGIN_SUCCESS",	//用户登录成功
	USER_LOGIN_FAIL:"USER_LOGIN_FAIL",	//用户登录失败
	USER_LOGOUT:"USER_LOGOUT",	//用户退出登录
	USER_REGISTER_SUCCESS:"USER_REGISTER_SUCCESS",	//注册成功
	USER_REGISTER_FAIL:"USER_REGISTER_FAIL",	//注册失败
	SEARCH_REFRESH:'SEARCH_REFRESH',	//搜索
	SEARCH_REFRESH_FAIL:'SEARCH_REFRESH_FAIL',	//搜索失败
	SEARCH_REFRESH_SUCCESS:'SEARCH_REFRESH_SUCCESS',	//搜索成功
	SUBSCRIBE_Load_SUCCESS:'SUBSCRIBE_Load_SUCCESS',	//获取订阅信息成功
	SUBSCRIBE_Load_FAIL:'SUBSCRIBE_Load_FAIL',	//获取订阅信息成功
	SUBSCRIBE_SUCCESS:'SUBSCRIBE_SUCCESS',	//订阅成功
	SUBSCRIBE_FAIL:'SUBSCRIBE_FAIL', //订阅失败
	SUBCRIBE_HOME_INIT:'SUBCRIBE_HOME_INIT',//获取首页的默认订阅分类

}