export default {
	THEME_CHANGE: "THEME_CHANGE",	//改变主题
	THEME_INIT: "THEME_INIT",		//默认主题
	SHOW_THEME_VIEW: "SHOW_THEME_VIEW", //显示主题页
	HOME_REFRESH:'POPULAR_REFRESH',	//刷新
	HOME_REFRESH_FAIL:'POPULAR_REFRESH_FAIL',	//下拉刷新失败
	HOME_REFRESH_SUCCESS:'POPULAR_REFRESH_SUCCESS',	//下拉刷新成功
	HOME_LOAD_MORE_SUCCESS:'POPULAR_LOAD_MORE_SUCCESS',	// 上拉加载更多成功
	HOME_LOAD_MORE_FAIL:'POPULAR_LOAD_MORE_FAIL',	// 上拉加载更多失败
	NEWS_DETAIL:'NEWS_DETAIL',		//获取新闻详情页
	Foreign_REFRESH:'POPULAR_REFRESH',	//际取新闻刷新
	Foreign_REFRESH_FAIL:'POPULAR_REFRESH_FAIL',	//际取新闻下拉刷新失败
	Foreign_REFRESH_SUCCESS:'POPULAR_REFRESH_SUCCESS',	//际取新闻下拉刷新成功
	Foreign_LOAD_MORE_SUCCESS:'POPULAR_LOAD_MORE_SUCCESS',	// 际取新闻上拉加载更多成功
	Foreign_LOAD_MORE_FAIL:'POPULAR_LOAD_MORE_FAIL',	// 际取新闻上拉加载更多失败
	Foreign_DETAIL:'NEWS_DETAIL',		//获国际取新闻详情页
}